# Step 01: Regression

In [96]:
import warnings
warnings.filterwarnings('ignore')

In [97]:
import pandas as pd
import numpy as np
df1 = pd.read_csv('weight-height - weight-height.csv')
df1.head()

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [98]:
df2 = df1.copy()
df3 = df1.copy()
df4 = df1.copy()
df5 = df1.copy()
df6 = df1.copy()
df7 = df1.copy()
df8 = df1.copy()

2. Separate x(Gender, Height) and y (y=Weight)
3. Train = 70%, Test = 30%
4. Apply Linear Regression
5. Evaluate the Model (Testing and training Accuracy, MSE for testing)
6. Apply KNN Regressor: https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsRegressor.html
7. Evaluate the Model (Testing and training Accuracy, MSE for testing)
8. Compare KNN & Linear regression with the KNN model and Linear regression as well.


Work from here..

In [99]:
dummies = pd.get_dummies(df2.Gender, drop_first=True)
dummies.head()

Male
0     1
1     1
2     1
3     1
4     1

In [100]:
df2.drop(df2[['Gender']],axis=1,inplace=True)

In [101]:
df2.head()

Height      Weight
0  73.847017  241.893563
1  68.781904  162.310473
2  74.110105  212.740856
3  71.730978  220.042470
4  69.881796  206.349801

In [102]:
df2=pd.concat([df2,dummies],axis=1)
df2.head()

Height      Weight  Male
0  73.847017  241.893563     1
1  68.781904  162.310473     1
2  74.110105  212.740856     1
3  71.730978  220.042470     1
4  69.881796  206.349801     1

In [103]:
x = df2.drop('Weight', axis=1)
x.head()

Height  Male
0  73.847017     1
1  68.781904     1
2  74.110105     1
3  71.730978     1
4  69.881796     1

In [104]:
y = df2[['Weight']] 
y.head()

Weight
0  241.893563
1  162.310473
2  212.740856
3  220.042470
4  206.349801

In [105]:
from sklearn.model_selection import train_test_split as tts

In [106]:
xtrain,xtest, ytrain, ytest = tts(x,y,test_size=0.3, random_state=3) 
xtrain.head()

Height  Male
6104  66.504653     0
1757  68.423586     1
4570  68.015295     1
2235  73.071977     1
6763  62.159352     0

In [107]:
from sklearn.linear_model import LinearRegression

In [108]:
reg = LinearRegression()

In [109]:
reg.fit(xtrain,ytrain)

LinearRegression()

In [110]:
reg.predict([[73.847017,0]])

array([[196.62048305]])

In [111]:
from sklearn.metrics import mean_squared_error

In [112]:
test_mse = mean_squared_error(ytest, reg.predict(xtest))
test_mse

103.26486729372274

In [113]:
reg.score(xtrain, ytrain)

0.8994768586222791

In [114]:
reg.score(xtest, ytest)

0.9008512093057297

# kNN Regressor

In [115]:
from sklearn.neighbors import KNeighborsRegressor

In [116]:
knn_regressor = KNeighborsRegressor(n_neighbors=2)

In [117]:
knn_regressor.fit(xtrain,ytrain)

KNeighborsRegressor(n_neighbors=2)

In [118]:
knn_regressor.predict([[73.847017 , 1]])

array([[218.31657225]])

In [119]:
y_pred = knn_regressor.predict(xtest)

In [120]:
xtest.head()

Height  Male
2333  61.461013     1
5677  66.615712     0
2717  73.696859     1
2824  72.744545     1
5324  66.640692     0

In [121]:
y_pred

array([[144.87640085],
       [162.5088169 ],
       [223.4321657 ],
       ...,
       [185.0613706 ],
       [215.37577755],
       [185.6650573 ]])

In [122]:
test_mse = mean_squared_error(ytest, y_pred)
test_mse

156.8625736140256

In [123]:
knn_regressor.score(xtrain, ytrain)

0.9491546066363276

In [124]:
knn_regressor.score(xtest, ytest)

0.8493898758927956

According to test accuracy Linear regression has better result than Knn regressor

# Step 02: Classification

In [125]:
df3.head()

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

2. Separate x and (y=Gender)
3. Train = 70%, Test = 30%
4. Apply KNN Classifier 
5. Evaluate the Model by only Accuracy.
6. Apply KNN Classifier: https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html

Work from here..

In [126]:
y= df3[['Gender']]
y.head()

Gender
0   Male
1   Male
2   Male
3   Male
4   Male

In [127]:
x = df3.drop(df3[['Gender']] , axis =1)
x.head()

Height      Weight
0  73.847017  241.893563
1  68.781904  162.310473
2  74.110105  212.740856
3  71.730978  220.042470
4  69.881796  206.349801

In [128]:
from sklearn.model_selection import train_test_split  as tts

In [129]:
xtrain , xtest ,ytrain , ytest = tts(x,y,test_size = .30 ,random_state = 3  )

In [130]:
from sklearn.neighbors import KNeighborsClassifier
kneigh = KNeighborsClassifier(n_neighbors=5)

In [131]:
kneigh.fit(xtrain, ytrain)

KNeighborsClassifier()

In [132]:
kneigh.predict([[72.385301, 189.165592]])

array(['Male'], dtype=object)

In [133]:
kneigh.score(xtest,ytest)

0.9088430074016361

In [134]:
knn = KNeighborsClassifier(n_neighbors=5, p=1, weights='distance')
knn.fit(xtrain, ytrain)
knn.predict([[72.385301, 189.165592]])
knn.score(xtest,ytest)

0.9018309310479159

In [135]:
knn2 = KNeighborsClassifier(n_neighbors=5, p=1)
knn2.fit(xtrain, ytrain)
knn2.predict([[72.385301, 189.165592]])
knn2.score(xtest,ytest)
#BEST ACCURACY WHEN P=1 AND WEIGHT='UNIFORM'

0.9096221269964939

In [136]:
knn3 = KNeighborsClassifier(n_neighbors=5, weights='distance')
knn3.fit(xtrain, ytrain)
knn3.predict([[72.385301, 189.165592]])
knn3.score(xtest,ytest)

0.8998831320607713